name: Build Artifacts

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.0.0
          cache: npm

      - name: Install NPM Packages
        run: npm run npm:clean-install

      - name: Configure Windows x64 only
        working-directory: app/electron
        shell: pwsh
        run: |
          $file = "./scripts/deploy-app.mjs"

          $content = Get-Content $file -Raw

          # Remove the Electron ARM64 build.
          $content = $content -replace `
            "(?ms)\s*dirTemp = await redist\(electronVersion, process\.platform, 'arm64'\);\s*await portable\.bundle\(dirApp, dirRes, dirTemp, dirOut\);", ""

          # Remove commented ARM64 setup lines as well.
          $content = $content -replace `
            "(?ms)\s*//dirTemp = await redist\(electronVersion, process\.platform, 'arm64'\);\s*//await setup\.bundle\(dirApp, dirTemp\);", ""

          Set-Content $file $content -NoNewline

      - name: Build Electron Windows x64
        run: npm run bundle --workspace app/electron

      - name: Upload Electron Windows x64
        uses: actions/upload-artifact@v4
        with:
          name: haruneko-electron-windows-x64
          retention-days: 7
          path: app/electron/bundle/*x64.zip
          if-no-files-found: error


  build-linux:
    name: Build Linux x64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.0.0
          cache: npm

      - name: Install NPM Packages
        run: npm run npm:clean-install

      - name: Setup Snapcraft
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo systemctl start snapd
          sudo snap install snapcraft --classic

      - name: Disable Snap Store upload
        working-directory: app/electron
        run: |
          sed -i "/snapcraft upload/d" ./scripts/bundle-app-snap.mjs

      - name: Build Electron Linux x64
        run: npm run bundle --workspace app/electron

      - name: Upload Electron Linux x64
        uses: actions/upload-artifact@v4
        with:
          name: haruneko-electron-linux-x64
          retention-days: 7
          path: app/electron/bundle/*.snap
          if-no-files-found: error
